### ISSUE TITLE
keep loosing connection to smartthings

### ISSUE THREAD

**Issue by drparham** [StrykerSKS/SmartThingsPublic#21] opened 2016-02-02 15:11 UTC
![screenshot_2016-02-02-08-09-09](https://cloud.githubusercontent.com/assets/2704700/12753462/71966c1a-c984-11e5-9def-07f822d7f1c0.jpg)

Have gotten this messge a few times in the last 24 hours.

**Comment by StrykerSKS** [comment] 2016-02-02 15:38
Which version are you running? Are you using the released version or the Beta version?

If you are on a recent version of the Software the Version number is now shown in the SmartApp.

**Comment by ncsufire** [comment] 2016-02-02 16:11
I have had several disconnects today as well.  I am on version 0.8.0 of
smart connect thermostat and 0.8.0-rc of sensor
On Feb 2, 2016 10:38 AM, "Sean Schneyer" notifications@github.com wrote:

Which version are you running? Are you using the released version or the
Beta version?

If you are on a recent version of the Software the Version number is now
shown in the SmartApp.

**Comment by drparham** [comment] 2016-02-02 17:17
Im on the same versions as @ncsufire

**Comment by StrykerSKS** [comment] 2016-02-02 17:33
Okay, let me look into a bit deeper. If you happened to have any info from the Live Logs that would be helpful.

I have seen some cloud issues already again today, so it may just be broken schedulers on ST causing the problems. 

Since most people don't have a Live Log running all the time, I'm also going to add some hooks to save some of the state data that would normally go to the logs only. That will help facilitate troubleshooting moving forward.

**Comment by drparham** [comment] 2016-02-02 18:43
Had live logs open when I got another disconnect notification at 11:15am MNT:

```
 c8ea3070-ffef-4149-bcbe-cb435ecce191 11:16:17 AM: debug generateEvent(): parsing data [debugEventFromParent:pollChildren() - Unable to pollChildren() due to API not being connected]. F or C? F
c8ea3070-ffef-4149-bcbe-cb435ecce191 11:16:17 AM: debug Executing 'poll' using parent SmartApp
596e53fd-8cd7-4c31-bf92-ab5070b2a25c 11:16:17 AM: debug generateEvent(): parsing data [debugEventFromParent:pollChildren() - Unable to pollChildren() due to API not being connected]. F or C? F
596e53fd-8cd7-4c31-bf92-ab5070b2a25c 11:16:17 AM: debug Executing 'poll' using parent SmartApp
4a5c74d1-1b5a-491e-be35-7b5dc5c6d4d9 11:16:17 AM: error java.util.concurrent.TimeoutException: Execution time exceeded 20 app execution seconds: 74337278119722 @ line 1431
4a5c74d1-1b5a-491e-be35-7b5dc5c6d4d9 11:15:50 AM: debug generateEvent(): parsing data [debugEventFromParent:Time since last poll? 1.9320666666666668 -- atomicState.lastPoll == 1454436834735]. F or C? F
4a5c74d1-1b5a-491e-be35-7b5dc5c6d4d9 11:15:50 AM: debug Executing 'poll' using parent SmartApp 
```

**Comment by StrykerSKS** [comment] 2016-02-02 19:30
I should have been more explicit. The useful bits are usually from the "Ecobee (Connect)" app. And anything related to "lost", lostAPI, and Exception. Also helpful to see anything that says "Time since last token refresh" or "until expiry". 

I'm also seeing errors in my logs related to adding and deleting scheduled events. I have also confirmed that there are general scheduling issues on the ST platform right now.

**Comment by drparham** [comment] 2016-02-02 19:36
Will keep a look out for anything meeting that criteria. Everything seems to be working properly atm.

```
 47158f65-8604-4914-beb3-fd6b4ca01eee 12:06:45 PM: debug timeLeft until expiry (in min): 14.99135 
```

And 

```
 47158f65-8604-4914-beb3-fd6b4ca01eee 12:06:45 PM: debug Expires in 3599 seconds 
```

**Comment by drparham** [comment] 2016-02-03 16:20
```
 47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: debug getChildDevices(false), children=4
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: error apiLost() - notifying each child: Ecobee Sensor:Master of loss
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: error apiLost() - notifying each child: Ecobee Thermostat:Home of loss
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: error apiLost() - notifying each child: Ecobee Sensor:Kids' Room of loss
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: error apiLost() - notifying each child: Ecobee Sensor:Downstairs of loss
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: debug getChildDevices(false), children=4
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:08 PM: error Unscheduling Polling and refreshAuthToken. User MUST reintialize the connection with Ecobee by running the SmartApp and logging in again
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:07 PM: debug generateEventLocalParams() - Updating sensor data: ecobee_sensor-rs:100-N8PW
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:07 PM: debug generateEventLocalParams() - Updating sensor data: ecobee_sensor-rs:102-MPK9
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:07 PM: debug getChildDevices(false), children=4
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:07 PM: debug getChildDevices(false), children=4
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:06 PM: warn sendPushAndFeeds >> atomicState.timeSendPush: 1454436977556
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:06 PM: warn sendPushAndFeeds >> notificationMessage: is disconnected from SmartThings/Ecobee, because the access credential changed or was lost. Please go to the Ecobee (Connect) SmartApp and re-enter your account login credentials.
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:06 PM: error apiLost() - pollEcobeeAPI() - In HttpResponseException: Received data.stat.code of 14: Lost connection with APIs. unscheduling Polling and refreshAuthToken. User MUST reintialize the connection with Ecobee by running the SmartApp and logging in again
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:06 PM: error In HttpResponseException: Received data.stat.code of 14
47158f65-8604-4914-beb3-fd6b4ca01eee 1:10:06 PM: error pollEcobeeAPI() >> HttpResponseException occured. Exception info: groovyx.net.http.HttpResponseException: Internal Server Error StatusCode: 500 response? data: [status:[message:Authentication token has expired. Refresh your tokens. , code:14]] 
```

**Comment by StrykerSKS** [comment] 2016-02-05 22:31
Please try again with the latest version to see if that fixes the problem. Thanks.

**Comment by StrykerSKS** [comment] 2016-02-09 06:20
Please advise if you are still  having these issues.

**Comment by drparham** [comment] 2016-02-09 15:20
I had a bunch of issues in a row on Sunday around 4ish, but haven't had any other issues after that. (this was after upgrading to the newest version)

**Comment by StrykerSKS** [comment] 2016-02-09 15:36
Okay. I'll leave this closed for now but if it starts happening again for you please feel free to re-open this ticket.

**Comment by drparham** [comment] 2016-02-10 03:11
Happened to me twice tonight.

**Comment by StrykerSKS** [comment] 2016-02-10 03:15
Okay, can you pull up the IDE or the Debug Dashboard (in the app) and paste in the information in the apiLostDump field?

**Comment by drparham** [comment] 2016-02-10 03:15
Just happened again, let me dig around and see what i can find.

**Comment by drparham** [comment] 2016-02-10 03:31
So couldn't find a Debug Dashboard in the app. Also not sure what you mean by IDE? Live Logging? I also just pulled in your most recent update, looks like mostly visual changes?

**Comment by StrykerSKS** [comment] 2016-02-10 03:39
In the IDE you would go to My Location -> List SmartApps -> Ecobee.

In the app, you need to set the debug Level to 5 in the preferences and then the Debug Dashboard will appear for you (like magic!)

Yes, the latest update was mostly visual changes, there were a few tweaks to the watchdogs too.

What version were you on when it kept losing connection for you? Perhaps it was just an older version (I've been making a lot of updates lately trying to work out the kinks in the update).

**Comment by drparham** [comment] 2016-02-10 03:51
I had just done the update Sunday or Saturday before posting about the connectivity issues that I had on Sunday. And just updated tonight when i went to look for the live logs.

Ok, I have the debug level set to 5, and i see the debug dashboard. Don't see any useful information in there since i just turned it on, but will check next time i get the disconnect.

**Comment by StrykerSKS** [comment] 2016-03-01 04:46
@drparham I just pushed a major update that completely revamps the authentication token handling. Can you please update to the latest version and give it a shot. I've have a stable connection now for over two weeks on my test app.

**Comment by drparham** [comment] 2016-03-01 04:49
Just upgraded tonight, thanks for staying on this!

**Comment by StrykerSKS** [comment] 2016-03-08 05:20
Can I close this out now? My current code has been running for weeks now. And I have a test stub that has been running for almost a month.

**Comment by ncsufire** [comment] 2016-03-08 11:44
I just got a disconnect this morning (haven't updated the code).  I usually get disconnects after updating the software to a new version, any idea why?  When I made the last update I was unable to complete the process (kept getting network error), funny thing is that the thermostat worked!

**Comment by StrykerSKS** [comment] 2016-03-08 15:18
Well, this morning that was to be expected. As posted in the forum, there was server maintenance by Ecobee between 4-6 am Eastern time today. In most cases, the disconnect should have been temporary and should have recovered on its own (mine did).

**Comment by drparham** [comment] 2016-03-08 16:13
It seems to be running great for me now. Before Updating I had a few disconnects, but since being on the newest version I haven't had any surprises.

**Closed as completed** 2016-03-08 17:29 UTC
