### ISSUE TITLE
Losing Connection

### ISSUE THREAD

**Issue by rcpolaris** [StrykerSKS/SmartThingsPublic#48] opened 2016-02-29 15:06 UTC
Hello, 
I am on version 0.9.9a and continue to get disconnected. Several times a day. It's almost been every hour or two...

**Comment by StrykerSKS** [comment] 2016-02-29 18:10
Please update to the 0.9.13 release that came out yesterday. It has a completely overhauled authentication handling that should solve this problem.

**Comment by StrykerSKS** [comment] 2016-03-01 04:17
Duplicate of #21

**Closed as completed by StrykerSKS** 2016-03-01 04:17 UTC
Labels: duplicate
